-- DTO Patent Database — 80 verified entries
-- Run AFTER schema.sql

INSERT INTO patents
  (name, sector, description, holder, access_type, available_since,
   saving, countries, source_link, notes, confidence, verified_date,
   tags, implementation_difficulty, is_published)
VALUES

-- ══ PHARMACEUTICALS (18) ══════════════════════════════════
('Amlodipine Besylate','Pharmaceuticals',
 'Calcium channel blocker API for hypertension treatment. One of Africa''s most prescribed cardiovascular medications — currently almost entirely imported despite the manufacturing process being public domain since 2007.',
 'Pfizer Inc.','Public Domain','2007','40–70% cost reduction',
 'Pan-African — especially Nigeria, South Africa, Kenya, Ghana, Egypt, Morocco',
 'https://patents.google.com',
 'Full synthesis specifications available via USPTO. Each country''s regulatory authority must approve before manufacturing: NAFDAC (Nigeria), SAHPRA (South Africa), PPB (Kenya), GRA (Ghana), EDA (Egypt). WHO prequalification pathway available.',
 'DTO Verified','May 2026',
 ARRAY['cardiovascular','hypertension','API','chronic disease'],'Low',true),

('Metformin Hydrochloride','Pharmaceuticals',
 'Biguanide API for Type 2 diabetes — one of the most prescribed drugs globally. Fully generic for over 30 years. Type 2 diabetes prevalence is rising rapidly across urban Africa due to dietary changes and urbanisation.',
 'Various (original patents 1920s)','Public Domain','1990s','60–80% cost reduction',
 'Pan-African',
 'https://patents.google.com',
 'Complete synthesis specifications freely available. WHO prequalification documentation contains full manufacturing guidance. Simple manufacturing process suitable for mid-scale African producers.',
 'DTO Verified','May 2026',
 ARRAY['diabetes','API','chronic disease','endocrine'],'Low',true),

('Artemether + Lumefantrine (ACT)','Pharmaceuticals',
 'WHO first-line artemisinin combination therapy for malaria. Africa accounts for 94% of global malaria deaths — 249 million cases in 2022. Fewer than 30 companies produce it locally despite the patent being pooled since 2009.',
 'Novartis AG','Patent Pool','Pooled 2009','50–65% cost reduction',
 'Pan-African malaria-endemic regions — Nigeria, DRC, Tanzania, Uganda, Mozambique, Ghana',
 'https://medicinespatentpool.org',
 'Apply via Medicines Patent Pool for a free sublicence. WHO prequalification pathway well established. PEPFAR and Global Fund supply chains available for qualifying manufacturers.',
 'DTO Verified','May 2026',
 ARRAY['malaria','ACT','artemisinin','MPP','tropical disease'],'Medium',true),

('Amoxicillin Trihydrate','Pharmaceuticals',
 'Broad-spectrum penicillin-class antibiotic universally prescribed across Africa. Manufacturing specifications fully public domain for decades.',
 'Beecham Group (now GSK)','Public Domain','1980s','55–75% cost reduction',
 'Pan-African',
 'https://patents.google.com',
 'No licence required. WHO prequalification documentation contains full manufacturing specifications. Strong candidate for regional production under AfCFTA health manufacturing initiative.',
 'DTO Verified','May 2026',
 ARRAY['antibiotic','penicillin','respiratory','paediatric'],'Low',true),

('Efavirenz — ARV First-Line HIV Treatment','Pharmaceuticals',
 'Non-nucleoside reverse transcriptase inhibitor for HIV/AIDS. Sub-Saharan Africa carries 67% of the global HIV burden — approximately 25 million people. All African nations qualify for compulsory licensing under WTO TRIPS Article 31.',
 'Bristol-Myers Squibb','Compulsory License','TRIPS Art.31 / MPP','65–85% cost reduction',
 'Pan-African — especially South Africa, Nigeria, Kenya, Uganda, Tanzania, Zimbabwe',
 'https://medicinespatentpool.org',
 'Medicines Patent Pool holds sublicences — fastest access route. Compulsory licensing requires national government action under TRIPS Article 31. Independent legal advice essential before proceeding.',
 'Legal Review Required','May 2026',
 ARRAY['HIV','ARV','antiretroviral','TRIPS','compulsory license'],'High',true),

('Tenofovir Disoproxil Fumarate (TDF)','Pharmaceuticals',
 'Nucleotide reverse transcriptase inhibitor — backbone of HIV treatment globally and increasingly used for Hepatitis B. Medicines Patent Pool holds sublicences for generic production in developing countries.',
 'Gilead Sciences','Patent Pool','MPP sublicence available','60–80% cost reduction',
 'Pan-African — especially South Africa, Nigeria, Kenya, Uganda, Ethiopia, Tanzania',
 'https://medicinespatentpool.org',
 'Apply via Medicines Patent Pool — sublicences available for manufacturers in developing countries. WHO prequalification required for export to PEPFAR-funded programmes.',
 'DTO Verified','May 2026',
 ARRAY['HIV','ARV','antiretroviral','hepatitis B','MPP'],'Medium',true),

('Ciprofloxacin Hydrochloride','Pharmaceuticals',
 'Broad-spectrum fluoroquinolone antibiotic widely used across Africa for bacterial infections including typhoid, UTIs, and respiratory infections. Bayer''s patent expired in 2004.',
 'Bayer AG','Public Domain','2004','50–70% cost reduction',
 'Pan-African',
 'https://patentscope.wipo.int',
 'Full synthesis route available via USPTO and Espacenet — freely accessible. WHO prequalification pathway available. No licence required from Bayer.',
 'DTO Verified','May 2026',
 ARRAY['antibiotic','fluoroquinolone','typhoid','bacterial infection'],'Low',true),

('Paracetamol (Acetaminophen) API','Pharmaceuticals',
 'One of the most used analgesics and antipyretics globally. Manufacturing process in the public domain for over 60 years. First medicine given to children with fever across Africa.',
 'Various (original patents pre-1960)','Public Domain','Pre-1960','60–80% cost reduction',
 'Pan-African',
 'https://patents.google.com',
 'Full synthesis specifications freely available — no licence required. Simple two-step manufacturing process. Suitable for small to mid-scale African manufacturers.',
 'DTO Verified','May 2026',
 ARRAY['analgesic','antipyretic','paediatric','fever','OTC'],'Low',true),

('Oral Rehydration Salts (ORS)','Pharmaceuticals',
 'WHO-recommended treatment for dehydration from diarrhoea — a leading killer of children under 5 across Africa. ORS formula is fully in the public domain and one of the most cost-effective medical interventions known.',
 'WHO (public domain formula)','Public Domain','1970s','Eliminate import dependency for essential childhood medicine',
 'Pan-African — especially East and Central Africa',
 'https://www.who.int',
 'WHO formula completely open — no licensing required. UNICEF provides free technical guidance. Suitable for community-scale production.',
 'DTO Verified','May 2026',
 ARRAY['diarrhoea','paediatric','rehydration','child mortality','OTC'],'Low',true),

('Doxycycline Hyclate','Pharmaceuticals',
 'Tetracycline antibiotic widely used for malaria prophylaxis, respiratory infections, STIs, and cholera treatment across Africa. All core manufacturing patents expired.',
 'Various (original patents pre-1970)','Public Domain','Pre-1970','55–75% cost reduction',
 'Pan-African',
 'https://patents.google.com',
 'Full synthesis specifications freely available via USPTO. Used extensively in malaria-endemic regions for prophylaxis.',
 'DTO Verified','May 2026',
 ARRAY['antibiotic','malaria','prophylaxis','cholera','STI'],'Low',true),

('Cotrimoxazole (Sulfamethoxazole + Trimethoprim)','Pharmaceuticals',
 'Combined antibiotic used extensively across Africa for HIV-related opportunistic infections, pneumonia, and typhoid. A cornerstone medicine in HIV care programmes. All core patents expired for over 30 years.',
 'Various (original patents pre-1970)','Public Domain','Pre-1970','60–80% cost reduction',
 'Pan-African — especially HIV-endemic regions',
 'https://patents.google.com',
 'No licence required. WHO prequalification pathway available.',
 'DTO Verified','May 2026',
 ARRAY['antibiotic','HIV','opportunistic infection','pneumonia','typhoid'],'Low',true),

('Metronidazole','Pharmaceuticals',
 'Antiprotozoal and antibiotic essential for treating amoebic dysentery, giardiasis, and bacterial vaginosis. Extremely common prescription across Africa. All core patents expired for decades.',
 'Rhône-Poulenc (original)','Public Domain','Pre-1980','55–70% cost reduction',
 'Pan-African',
 'https://patents.google.com',
 'Full synthesis specifications in public domain. WHO prequalification pathway available.',
 'DTO Verified','May 2026',
 ARRAY['antibiotic','antiprotozoal','dysentery','giardiasis'],'Low',true),

('Fluconazole','Pharmaceuticals',
 'Antifungal medicine critical for treating cryptococcal meningitis — a leading cause of death in HIV-positive patients across Africa. Core patents expired in most African jurisdictions.',
 'Pfizer Inc.','Patent Pool','MPP / expired in most African jurisdictions','65–80% cost reduction',
 'Pan-African — especially sub-Saharan HIV-endemic regions',
 'https://medicinespatentpool.org',
 'Medicines Patent Pool sublicences available. WHO prequalification pathway available.',
 'DTO Verified','May 2026',
 ARRAY['antifungal','HIV','meningitis','MPP'],'Medium',true),

('Ibuprofen API','Pharmaceuticals',
 'Non-steroidal anti-inflammatory drug (NSAID) widely used for pain, fever, and inflammation. All core manufacturing patents expired.',
 'Boots Company PLC (original)','Public Domain','1990s','50–70% cost reduction',
 'Pan-African',
 'https://patents.google.com',
 'Full synthesis specifications freely available. WHO prequalification pathway available.',
 'DTO Verified','May 2026',
 ARRAY['NSAID','analgesic','anti-inflammatory','OTC'],'Low',true),

('Lamivudine (3TC)','Pharmaceuticals',
 'Nucleoside reverse transcriptase inhibitor — one of the most widely used ARVs globally and a cornerstone of HIV treatment. Also used for Hepatitis B treatment.',
 'ViiV Healthcare / GSK','Patent Pool','MPP sublicence available','60–80% cost reduction',
 'Pan-African — especially South Africa, Nigeria, Kenya, Uganda, Ethiopia',
 'https://medicinespatentpool.org',
 'Medicines Patent Pool sublicences available for manufacturers in developing countries.',
 'DTO Verified','May 2026',
 ARRAY['HIV','ARV','antiretroviral','hepatitis B','MPP'],'Medium',true),

('Artemisinin — Raw API Extraction','Pharmaceuticals',
 'The active ingredient in first-line malaria treatment. Extraction and purification processes are in the public domain. Africa grows Artemisia annua in Uganda, Tanzania, Rwanda, Kenya — but exports raw plant rather than processing the API domestically.',
 'Various (extraction processes public domain)','Public Domain','Core processes pre-1990',
 'Capture API value domestically — currently exported as raw plant material',
 'Uganda, Tanzania, Rwanda, Kenya, DRC, Ethiopia',
 'https://patentscope.wipo.int',
 'UNITAID and Medicines for Malaria Venture provide technical advisory for African producers.',
 'DTO Verified','May 2026',
 ARRAY['malaria','artemisinin','API extraction','agro-processing'],'High',true),

('Quinine Sulfate','Pharmaceuticals',
 'Used for severe malaria and as a second-line treatment. All synthesis and extraction patents expired. DRC, Rwanda, and Burundi historically produced cinchona bark domestically.',
 'Various (original patents pre-1940)','Public Domain','Pre-1940',
 'Eliminate import dependency for malaria treatment API',
 'DRC, Rwanda, Burundi, Uganda, Tanzania',
 'https://patents.google.com',
 'All quinine synthesis and extraction patents fully expired. WHO prequalification pathway available.',
 'DTO Verified','May 2026',
 ARRAY['malaria','quinine','API extraction','alkaloid'],'Medium',true),

('Zinc Sulfate — Paediatric Diarrhoea Treatment','Pharmaceuticals',
 'WHO-recommended zinc supplementation for paediatric diarrhoea — proven to reduce duration and severity by 25%. Simple mineral processing. Critical for reducing child mortality across Africa.',
 'Various (effectively public domain)','Public Domain','Effectively pre-1990',
 'Eliminate import dependency for essential paediatric medicine',
 'Pan-African — especially DRC, Nigeria, Ethiopia, Tanzania, Niger',
 'https://www.who.int',
 'Simple zinc sulfate formulation — no licence required. WHO and UNICEF provide free technical guidance.',
 'DTO Verified','May 2026',
 ARRAY['zinc','paediatric','diarrhoea','micronutrient','child mortality'],'Low',true),

-- ══ ENERGY (8) ═══════════════════════════════════════════
('Combined-Cycle Gas Turbine (CCGT) — Pre-2003 Configurations','Energy',
 'Highly efficient power generation combining gas and steam turbines. Core GE, Westinghouse, and Siemens configurations whose patents expired pre-2003 are now fully in the public domain. Nigeria''s grid delivers only 32% of installed capacity.',
 'GE / Westinghouse / Siemens (pre-2003)','Public Domain','1990s–2000s',
 'Significant reduction in power plant technology licensing cost',
 'Nigeria, Ghana, Senegal, Côte d''Ivoire, Cameroon, Egypt, Tanzania, Mozambique',
 'https://patentscope.wipo.int',
 'Focus on pre-2003 CCGT configurations — these are verified expired. Contact WIPO GREEN for technology transfer connections.',
 'DTO Verified','May 2026',
 ARRAY['power generation','gas turbine','CCGT','energy infrastructure'],'High',true),

('First & Second Generation Solar PV Cell Manufacturing','Energy',
 'Solar photovoltaic cell manufacturing processes. All first and second-generation PV patents expired. Africa imported approximately $2 billion in solar PV modules in 2023 despite having the world''s highest solar irradiation.',
 'Bell Labs / various','Public Domain','1980s–1990s',
 'Build local solar supply chain — reduce $2B annual PV import cost',
 'Pan-African — especially South Africa, Morocco, Egypt, Nigeria, Kenya, Ethiopia',
 'https://patents.google.com',
 'Contact WIPO GREEN for technology transfer connections. South Africa''s REIPPP programme creates demand for locally manufactured components.',
 'DTO Verified','May 2026',
 ARRAY['solar','PV','renewable energy','photovoltaic','manufacturing'],'High',true),

('Small Hydropower — Run-of-River Turbine Designs','Energy',
 'Run-of-river small hydropower systems under 10MW. Core engineering designs fully in the public domain. DRC alone holds 13% of global hydropower potential.',
 'Various (original designs pre-1970)','Public Domain','Pre-1970',
 'Provide reliable off-grid power to rural African communities at minimal technology cost',
 'DRC, Ethiopia, Rwanda, Uganda, Cameroon, Mozambique, Tanzania, Kenya, Zambia, Zimbabwe',
 'https://patentscope.wipo.int',
 'Full engineering specifications via UNIDO''s Small Hydropower Programme.',
 'DTO Verified','May 2026',
 ARRAY['hydropower','renewable energy','rural electrification','off-grid'],'Medium',true),

('Biogas Anaerobic Digestion Systems','Energy',
 'Anaerobic digestion technology converting agricultural and organic waste into biogas. Core digester designs fully public domain. Applicable wherever agriculture produces organic waste.',
 'Various (original patents 1950s–70s)','Public Domain','Pre-1980',
 'Eliminate LPG and firewood costs — reduce deforestation across rural Africa',
 'Pan-African — especially Ethiopia, Kenya, Uganda, Rwanda, Ghana, Nigeria, Tanzania',
 'https://patentscope.wipo.int',
 'Full biogas digester specifications available from FAO and UNIDO.',
 'DTO Verified','May 2026',
 ARRAY['biogas','anaerobic digestion','waste-to-energy','rural energy','deforestation'],'Low',true),

('Wind Turbine — Horizontal Axis Designs Pre-1995','Energy',
 'Horizontal axis wind turbine designs from Danish and German manufacturers. Core aerodynamic and mechanical designs from the 1980s–early 1990s are fully expired.',
 'Vestas / Bonus Energy / various (pre-1995)','Public Domain','Pre-1995',
 'Access wind energy technology design specifications at zero licensing cost',
 'Morocco, South Africa, Ethiopia, Kenya, Egypt, Tunisia, Mozambique, Tanzania',
 'https://patents.google.com',
 'Pre-1995 horizontal axis wind turbine designs fully expired.',
 'DTO Verified','May 2026',
 ARRAY['wind energy','renewable energy','turbine','mechanical engineering'],'High',true),

('Lead-Acid Battery Manufacturing','Energy',
 'Industrial lead-acid battery production technology. Core manufacturing processes fully public domain. Africa holds significant lead ore deposits in Zambia, South Africa, Morocco, and Namibia.',
 'Planté / Faure (original inventors), various','Public Domain','Pre-1970',
 'Build domestic battery supply chain utilising Africa''s own lead ore deposits',
 'Pan-African — especially Zambia, South Africa, Morocco, Nigeria, Kenya, Namibia',
 'https://patents.google.com',
 'Contact UNIDO for industrial battery manufacturing advisory.',
 'DTO Verified','May 2026',
 ARRAY['battery','energy storage','lead','mining value chain'],'Medium',true),

('Ethanol Fuel Production from Cassava & Sugarcane','Energy',
 'Fermentation and distillation processes for producing fuel-grade ethanol. All core process patents expired. Brazil''s EMBRAPA shares sugarcane ethanol technology freely with African nations.',
 'Various / EMBRAPA Brazil','Public Domain','Pre-1990',
 'Produce domestic fuel from agricultural biomass — reduce fossil fuel import dependency',
 'Nigeria, Ghana, Côte d''Ivoire, DRC, Tanzania, Kenya, Ethiopia, Zambia',
 'https://patentscope.wipo.int',
 'EMBRAPA Brazil shares ethanol production technology with Africa freely.',
 'DTO Verified','May 2026',
 ARRAY['biofuel','ethanol','sugarcane','cassava','fermentation'],'Medium',true),

('Jatropha Biodiesel Production','Energy',
 'Production of biodiesel from Jatropha curcas — a drought-resistant non-food oilseed crop that grows on marginal land across tropical Africa. Transesterification process fully public domain.',
 'Various (transesterification pre-1960)','Public Domain','Pre-1990 (application)',
 'Produce domestic diesel substitute from marginal African land',
 'Mali, Burkina Faso, Senegal, Tanzania, Kenya, Mozambique, Zimbabwe, Zambia, South Africa',
 'https://patentscope.wipo.int',
 'UNIDO has supported Jatropha biodiesel projects across Africa.',
 'DTO Verified','May 2026',
 ARRAY['biofuel','biodiesel','jatropha','marginal land','transesterification'],'Medium',true),

-- ══ STEEL & MANUFACTURING (5) ════════════════════════════
('Basic Oxygen Furnace (BOF) Steelmaking','Steel & Manufacturing',
 'Primary method for producing steel from iron ore. All core patents expired pre-1990. Africa exports raw iron ore and imports finished steel — this gap costs billions annually.',
 'Various (original 1950s–70s)','Public Domain','Pre-1990',
 'Eliminate technology licensing on domestic steel production',
 'South Africa, Nigeria, Egypt, Algeria, Ethiopia, Zimbabwe, Kenya, Tanzania',
 'https://patents.google.com',
 'Contact UNIDO Industrial Development office.',
 'DTO Verified','May 2026',
 ARRAY['steel','iron','smelting','heavy industry','BOF'],'High',true),

('Electric Arc Furnace (EAF) Steelmaking from Scrap','Steel & Manufacturing',
 'Steel production using electric arc furnaces processing scrap steel. Core EAF designs fully public domain. EAF requires less capital than BOF — ideal for emerging African steel producers.',
 'Various (original 1900s–1950s)','Public Domain','Pre-1960',
 'Produce domestic steel from urban scrap metal — circular economy opportunity',
 'South Africa, Nigeria, Egypt, Kenya, Ghana, Algeria, Morocco, Ethiopia',
 'https://patents.google.com',
 'Lower capital requirement than BOF. Urban scrap metal is increasingly available across African cities.',
 'DTO Verified','May 2026',
 ARRAY['steel','EAF','scrap metal','circular economy','recycling'],'High',true),

('Fluid Catalytic Cracking (FCC) — Petroleum Refining','Steel & Manufacturing',
 'Core petroleum refining process converting crude oil into petrol, diesel, and other products. Fundamental FCC patents from 1940s–1970s fully expired. Nigeria spends billions annually importing refined petroleum.',
 'Standard Oil / UOP (original 1940s–70s)','Public Domain','Pre-1980',
 'Capture refining value — reduce fuel import costs across oil-producing African nations',
 'Nigeria, Angola, Libya, Algeria, Egypt, Ghana, Equatorial Guinea, Gabon, South Sudan',
 'https://patents.google.com',
 'Foundational FCC process designs public domain.',
 'DTO Verified','May 2026',
 ARRAY['petroleum','refining','FCC','downstream','oil & gas'],'High',true),

('CNC Machining — Foundational Control Designs','Steel & Manufacturing',
 'Computer numerical control (CNC) machining foundational designs and control architectures. Core patents from 1950s–1980s fully expired. Open-source CNC communities provide complete free designs.',
 'MIT / Various (original 1950s–80s)','Public Domain','Pre-1985',
 'Access precision manufacturing capability at zero licensing cost',
 'Pan-African — especially South Africa, Egypt, Morocco, Nigeria, Kenya',
 'https://openbuilds.com',
 'OpenBuilds provides complete open-source CNC designs. LinuxCNC provides free control software.',
 'DTO Verified','May 2026',
 ARRAY['CNC','precision manufacturing','open source','machining','tooling'],'Medium',true),

('Aluminium Smelting — Hall-Héroult Process','Steel & Manufacturing',
 'Electrolytic process for producing primary aluminium. All core Hall-Héroult patents expired for over 100 years. Guinea holds 25% of global bauxite reserves but exports raw bauxite.',
 'Hall / Héroult (original 1880s)','Public Domain','Pre-1910',
 'Capture aluminium smelting value from Africa''s 25% share of global bauxite reserves',
 'Guinea, Ghana, Sierra Leone, Cameroon, Mozambique, South Africa',
 'https://patents.google.com',
 'Hall-Héroult process completely public domain. Requires significant electricity — pair with hydropower.',
 'DTO Verified','May 2026',
 ARRAY['aluminium','smelting','bauxite','electrolysis','value chain'],'High',true),

-- ══ AGRICULTURE & FOOD PROCESSING (13) ══════════════════
('Sugarcane Ethanol & Sugar Refining Process','Agriculture & Food Processing',
 'Industrial sugar refining and ethanol production from sugarcane. Core EMBRAPA process patents expired pre-1995. Nigeria alone imported 1.7 million MT of raw sugar in 2025.',
 'Various / EMBRAPA Brazil / Dedini Industries','Public Domain','Pre-1995',
 'Eliminate raw sugar import dependency across Africa',
 'Nigeria, Kenya, South Africa, Ethiopia, Tanzania, Uganda, Zambia, Zimbabwe, Mozambique, Malawi',
 'https://patentscope.wipo.int',
 'EMBRAPA Brazil shares sugarcane technology with Africa freely.',
 'DTO Verified','May 2026',
 ARRAY['sugar','sugarcane','agro-processing','food security','ethanol'],'Medium',true),

('Edible Oil Refining — Palm, Sunflower, Groundnut & Soybean','Agriculture & Food Processing',
 'Industrial processes for refining vegetable oils. All core refining process patents expired. West Africa produces significant palm oil but imports refined products.',
 'Alfa Laval / Lurgi (original patents)','Public Domain','Pre-1990',
 '40–60% reduction in edible oil technology acquisition cost',
 'Nigeria, Ghana, Côte d''Ivoire, DRC (palm oil); Kenya, Ethiopia, Tanzania (sunflower/soy)',
 'https://patents.google.com',
 'Contact UNIDO Agro-Industries division for technical advisory.',
 'DTO Verified','May 2026',
 ARRAY['edible oil','palm oil','sunflower','groundnut','refining','agro-processing'],'Medium',true),

('Haber-Bosch Nitrogen Fertiliser Production','Agriculture & Food Processing',
 'Core industrial process for nitrogen-based fertilisers. In the public domain for over 60 years. Africa imports over 90% of its fertilisers despite having domestic gas, coal, and biomass feedstocks.',
 'BASF (original 1910s)','Public Domain','Pre-1960',
 'Eliminate fertiliser import dependency — strengthen African food security',
 'Pan-African — especially Nigeria, Egypt, Algeria, Mozambique, Tanzania, South Africa, Ethiopia, Kenya',
 'https://patentscope.wipo.int',
 'Full process specifications available from UNIDO.',
 'DTO Verified','May 2026',
 ARRAY['fertiliser','nitrogen','food security','agriculture','chemical'],'High',true),

('Tomato Paste & Vegetable Canning','Agriculture & Food Processing',
 'Industrial tomato and vegetable processing, concentration, and canning. All core patents expired. Nigeria loses 40–50% of its 1.8M MT tomato harvest annually to spoilage.',
 'Various — Italian and US canning industry','Public Domain','Pre-1980',
 'Capture $500M+ in value currently lost to post-harvest spoilage across Africa',
 'Nigeria, Ethiopia, Kenya, Ghana, Morocco, Egypt, Tanzania, South Africa, Senegal, Cameroon',
 'https://patents.google.com',
 'FAO TECA has validated preservation technologies for African nations.',
 'DTO Verified','May 2026',
 ARRAY['tomato','canning','post-harvest','food processing','spoilage'],'Medium',true),

('Flour Milling — Roller Mill Process','Agriculture & Food Processing',
 'Industrial wheat and grain flour milling. Core Bühler AG machinery patents expired pre-1980. Africa imports billions in wheat and flour annually.',
 'Bühler Group / various (original patents)','Public Domain','Pre-1980',
 'Reduce wheat processing technology acquisition cost by 50–70%',
 'Nigeria, Egypt, Morocco, Algeria, Ethiopia, Kenya, South Africa, Tunisia, Tanzania',
 'https://patents.google.com',
 'Egypt and Morocco already have significant milling industries that can serve as regional knowledge transfer hubs.',
 'DTO Verified','May 2026',
 ARRAY['flour','milling','wheat','grain','food processing'],'Medium',true),

('Fish Processing & Cold Chain','Agriculture & Food Processing',
 'Industrial fish processing including smoking, drying, chilling, and canning. Africa produces approximately 11 million tonnes of fish annually but loses 25–30% to spoilage.',
 'Various (original patents pre-1960)','Public Domain','Pre-1960',
 'Recover 25–30% of Africa''s annual fish production currently lost to spoilage',
 'Ghana, Nigeria, Senegal, Kenya, Tanzania, Mozambique, DRC, Angola, South Africa, Côte d''Ivoire',
 'https://patents.google.com',
 'Full fish processing specifications available via FAO''s Fishery Technology Division.',
 'DTO Verified','May 2026',
 ARRAY['fish','cold chain','post-harvest','food processing','fisheries'],'Medium',true),

('Cassava Processing — Starch, Flour & Ethanol Production','Agriculture & Food Processing',
 'Industrial processes for converting cassava to starch, flour, and ethanol. Cassava is the third-largest food crop in Africa — grown in 40+ countries. Nigeria is the world''s largest producer.',
 'Various (original patents pre-1980)','Public Domain','Pre-1980',
 'Triple the value captured from Africa''s third-largest food crop',
 'Nigeria, Ghana, DRC, Côte d''Ivoire, Tanzania, Uganda, Cameroon, Mozambique, Ethiopia',
 'https://patentscope.wipo.int',
 'Full cassava processing specifications available from FAO and IITA (headquartered in Nigeria).',
 'DTO Verified','May 2026',
 ARRAY['cassava','starch','flour','agro-processing','food security'],'Medium',true),

('Dairy Processing — Pasteurisation & UHT Treatment','Agriculture & Food Processing',
 'Milk pasteurisation and Ultra High Temperature (UHT) processing for extended shelf life. All core HTST and UHT processing patents expired. Africa loses enormous dairy quantities to spoilage.',
 'Various (original patents pre-1970)','Public Domain','Pre-1970',
 'Recover dairy value lost to spoilage — extend shelf life enabling broader market access',
 'Kenya, Ethiopia, Tanzania, Uganda, South Africa, Rwanda, Nigeria, Egypt, Morocco',
 'https://patents.google.com',
 'Kenya has East Africa''s most developed dairy processing industry and can serve as a regional knowledge hub.',
 'DTO Verified','May 2026',
 ARRAY['dairy','milk','pasteurisation','UHT','cold chain','food processing'],'Medium',true),

('Shea Butter Processing — Industrial Extraction','Agriculture & Food Processing',
 'Industrial extraction and refining of shea butter. The shea belt stretches across 21 sub-Saharan African countries. Global market worth $2+ billion annually — cosmetics, chocolate, pharmaceuticals.',
 'Various (original extraction patents pre-1960)','Public Domain','Pre-1960',
 'Capture shea butter processing value in Africa — processed shea commands 3–5x raw kernel price',
 'Ghana, Nigeria, Burkina Faso, Mali, Côte d''Ivoire, Senegal, Uganda, Cameroon, Niger, Benin',
 'https://patentscope.wipo.int',
 'Women''s cooperative processing organisations are the primary actors. Processed shea commands 3–5x raw kernel price.',
 'DTO Verified','May 2026',
 ARRAY['shea','cosmetics','women','cooperative','agro-processing','West Africa'],'Low',true),

('Cocoa Bean Processing — Fermentation, Drying & Grinding','Agriculture & Food Processing',
 'Industrial cocoa bean post-harvest processing. Africa produces 75% of global cocoa — primarily in Côte d''Ivoire, Ghana, Nigeria, Cameroon, Uganda. Yet most cocoa is exported as raw beans.',
 'Various (original processing patents pre-1960)','Public Domain','Pre-1960',
 'Retain cocoa processing value in Africa — capture the manufacturing margin on 75% of global cocoa production',
 'Côte d''Ivoire, Ghana, Nigeria, Cameroon, Uganda, Tanzania, Sierra Leone',
 'https://patents.google.com',
 'Processing cocoa beans into semi-finished products before export would dramatically increase African cocoa value retention.',
 'DTO Verified','May 2026',
 ARRAY['cocoa','chocolate','agro-processing','value chain','West Africa'],'Medium',true),

('Coffee Processing — Wet & Dry Milling','Agriculture & Food Processing',
 'Industrial coffee processing: wet and dry milling, hulling, grading, and roasting. Ethiopia is the birthplace of coffee. Kenya, Uganda, Tanzania, Rwanda, Burundi all produce globally traded speciality coffees. Most exported as green beans.',
 'Various (original milling and roasting patents pre-1960)','Public Domain','Pre-1960',
 'Retain coffee roasting and processing value in Africa',
 'Ethiopia, Uganda, Kenya, Tanzania, Rwanda, Burundi, DRC, Cameroon',
 'https://patents.google.com',
 'Rwanda''s Gorilla''s Coffee demonstrates premium export market access for African-roasted coffee.',
 'DTO Verified','May 2026',
 ARRAY['coffee','roasting','agro-processing','speciality','East Africa'],'Low',true),

('Beeswax & Honey Processing','Agriculture & Food Processing',
 'Industrial honey processing including filtration, pasteurisation, and packaging, plus beeswax processing for cosmetics, pharmaceuticals, and industrial applications. Ethiopia is Africa''s largest honey producer.',
 'Various (original processing patents pre-1960)','Public Domain','Pre-1960',
 'Triple the value captured from Africa''s honey and beeswax production',
 'Ethiopia, Tanzania, Kenya, Zambia, Uganda, Nigeria, South Africa, Ghana, Mozambique',
 'https://patentscope.wipo.int',
 'FAO freely available honey processing specifications. Beeswax has pharmaceutical, cosmetic, and industrial applications.',
 'DTO Verified','May 2026',
 ARRAY['honey','beeswax','apiculture','cosmetics','agro-processing'],'Low',true),

('Essential Oil Distillation — Steam Distillation Process','Agriculture & Food Processing',
 'Steam distillation of plant material to produce essential oils. Core steam distillation patents expired for over 100 years. Africa produces Moroccan argan, Malagasy ylang-ylang, South African buchu, Ethiopian frankincense. Most exported as raw plant material.',
 'Various (original steam distillation patents pre-1900)','Public Domain','Pre-1920',
 'Multiply value from Africa''s aromatic plants through essential oil extraction',
 'Morocco, South Africa, Madagascar, Ethiopia, Kenya, Tanzania, Tunisia, Algeria, Nigeria, Ghana',
 'https://patents.google.com',
 'Morocco''s argan oil industry demonstrates premium market potential.',
 'DTO Verified','May 2026',
 ARRAY['essential oils','distillation','aromatics','cosmetics','agro-processing'],'Low',true),

-- ══ TEXTILES & LEATHER (6) ═══════════════════════════════
('Ring Spinning — Cotton & Synthetic Yarn Production','Textiles & Leather',
 'Ring spinning is the dominant industrial process for producing yarn from cotton and synthetic fibres. Africa produces 1.8 million tonnes of cotton annually but most is exported unprocessed.',
 'Various — Swiss, German, Belgian machinery manufacturers','Public Domain','Pre-1970',
 'Access industrial yarn spinning technology at zero licensing cost',
 'Ethiopia, Egypt, Morocco, Ghana, Nigeria, Côte d''Ivoire, Tanzania, Kenya, Lesotho, South Africa',
 'https://patents.google.com',
 'Ethiopia''s Hawassa Industrial Park demonstrates viability — targeting $1B in textile exports annually.',
 'DTO Verified','May 2026',
 ARRAY['textiles','cotton','spinning','yarn','AGOA','manufacturing'],'Medium',true),

('Shuttle & Projectile Loom Weaving Technology','Textiles & Leather',
 'Industrial textile weaving using shuttle and projectile loom designs. All foundational patents expired. West Africa''s traditional textile industries can be industrialised using freely available loom technology.',
 'Various — Swiss, German, Belgian textile machinery','Public Domain','Pre-1970',
 'Access industrial textile weaving machinery designs at zero licensing cost',
 'Ethiopia, Ghana, Nigeria, Côte d''Ivoire, Kenya, Tanzania, Lesotho, Morocco, Egypt, South Africa',
 'https://patents.google.com',
 'Strong AGOA and EU market access for African textiles creates export demand.',
 'DTO Verified','May 2026',
 ARRAY['textiles','weaving','loom','fabric','AGOA','manufacturing'],'Medium',true),

('Chrome Leather Tanning Process','Textiles & Leather',
 'Chrome tanning is the dominant industrial process for converting raw animal hides into leather. Africa is the world''s largest producer of cattle hides and skins — yet exports most raw hides at low value.',
 'Various (original patents 1880s–1940s)','Public Domain','Pre-1950',
 'Multiply the value of Africa''s hide and skin exports',
 'Ethiopia, Kenya, Nigeria, Tanzania, South Africa, Sudan, Somalia, Zimbabwe, Mozambique, Uganda',
 'https://patents.google.com',
 'UNIDO Leather Programme provides free technical advisory for African tanneries.',
 'DTO Verified','May 2026',
 ARRAY['leather','tanning','hides','footwear','value chain'],'Medium',true),

('Vegetable Tanning — Plant-Based Leather Process','Textiles & Leather',
 'Traditional vegetable tanning using plant-derived tannins. Completely public domain. Africa''s acacia species produce excellent tanning agents. South Africa is a major global wattle bark producer.',
 'Traditional knowledge — fully public domain','Public Domain','Pre-1900',
 'Produce premium vegetable-tanned leather — access luxury leather markets at 3–5x chrome-tanned price',
 'South Africa (wattle), Kenya, Tanzania, Ethiopia, Zimbabwe, Zambia, Morocco, Nigeria',
 'https://patents.google.com',
 'Completely public domain — no IP concerns whatsoever. Vegetable-tanned leather commands premium prices in European luxury goods markets.',
 'DTO Verified','May 2026',
 ARRAY['leather','vegetable tanning','luxury','wattle','sustainable'],'Low',true),

('Synthetic Rubber Compounding — Shoe Sole Manufacturing','Textiles & Leather',
 'Rubber compounding processes for manufacturing shoe soles. Core vulcanisation and compounding patents expired for over 100 years. Africa imports most footwear despite having leather, natural rubber, and manufacturing capability.',
 'Various (Goodyear vulcanisation patent expired 1858)','Public Domain','Pre-1960',
 'Complete the leather-to-shoe value chain domestically',
 'Ethiopia, Kenya, South Africa, Nigeria, Ghana, Tanzania, Morocco, Egypt',
 'https://patents.google.com',
 'Natural rubber from West Africa provides domestic raw material. Ethiopia and Kenya already have footwear manufacturing.',
 'DTO Verified','May 2026',
 ARRAY['footwear','rubber','vulcanisation','shoe manufacturing','value chain'],'Medium',true),

('Sisal & Natural Fibre Rope & Twine Manufacturing','Textiles & Leather',
 'Industrial processing of sisal, jute, kenaf, and other natural fibres into rope, twine, mats, and industrial textiles. Tanzania is the world''s second-largest sisal producer after Brazil.',
 'Various (original fibre processing patents pre-1950)','Public Domain','Pre-1960',
 'Add manufacturing value to Africa''s natural fibre production',
 'Tanzania, Kenya, Madagascar, Mozambique, Ethiopia, South Africa, Nigeria, Angola, Zimbabwe',
 'https://patents.google.com',
 'Natural fibre ropes and matting are growing in demand for sustainable packaging and construction markets.',
 'DTO Verified','May 2026',
 ARRAY['sisal','natural fibre','rope','sustainable','packaging','East Africa'],'Low',true),

-- ══ AUTOMOTIVE (3) ═══════════════════════════════════════
('Compressed Natural Gas (CNG) Vehicle Conversion Systems','Automotive',
 'CNG fuel system components and vehicle conversion technology. Core patents from 1980s–early 2000s now expired. Nigeria''s Innoson is commissioning the world''s largest CNG vehicle plant in 2026.',
 'Various — Italian FIAT / New Zealand CNG industry (1980s–90s)','Public Domain','Pre-2005',
 'Reduce CNG vehicle technology licensing cost by 60–80%',
 'Nigeria, Tanzania, Mozambique, South Africa, Algeria, Egypt, Ethiopia, Cameroon',
 'https://patentscope.wipo.int',
 'Italian CNG vehicle conversion system patents from 1980s–90s fully expired and verified.',
 'DTO Verified','May 2026',
 ARRAY['automotive','CNG','gas vehicle','Innoson','clean transport'],'Medium',true),

('Four-Stroke Internal Combustion Engine Assembly','Automotive',
 'Fundamental four-stroke internal combustion engine design and assembly specifications. All core patents expired over 70 years ago. South Africa has the most developed automotive sector; Nigeria''s Innoson is the most prominent indigenous manufacturer.',
 'Otto / Benz / various (original 1800s–1950s)','Public Domain','Pre-1950',
 'Zero licensing cost on core engine assembly technology',
 'South Africa, Nigeria, Kenya, Ethiopia, Ghana, Morocco, Egypt, Tunisia',
 'https://patents.google.com',
 'Nigeria''s Innoson demonstrates indigenous vehicle manufacturing viability.',
 'DTO Verified','May 2026',
 ARRAY['automotive','engine','assembly','manufacturing','Innoson'],'High',true),

('Bicycle Frame Manufacturing & Assembly','Automotive',
 'Industrial bicycle frame design and assembly. All foundational patents expired for over 100 years. Rwanda''s bicycle industry is a model — producing bikes domestically and exporting across East Africa.',
 'Various (original patents 1880s–1920s)','Public Domain','Pre-1930',
 'Build domestic bicycle manufacturing — Africa''s most accessible transport technology',
 'Rwanda, Kenya, Uganda, Ghana, South Africa, Ethiopia, Tanzania, Nigeria, Senegal',
 'https://patents.google.com',
 'Rwanda''s bicycle factory demonstrates modern manufacturing viability.',
 'DTO Verified','May 2026',
 ARRAY['bicycle','transport','low-tech manufacturing','Rwanda','East Africa'],'Low',true),

-- ══ DIGITAL INFRASTRUCTURE (4) ══════════════════════════
('OpenSSL Cryptographic Security Library','Digital Infrastructure',
 'Industry-standard open-source cryptographic library for securing internet communications. Free to use, modify, and deploy. Africa''s fintech sector is rapidly expanding — Nigeria alone accounts for 28% of African fintech companies.',
 'OpenSSL Project (open source)','Public Domain','1998 (ongoing)',
 'Zero licensing cost vs proprietary security alternatives',
 'Pan-African',
 'https://openssl.org',
 'Pairs with NIST Cybersecurity Framework (also free) for comprehensive security.',
 'DTO Verified','May 2026',
 ARRAY['cybersecurity','cryptography','open source','fintech','digital infrastructure'],'Low',true),

('Open-Source GSM / Mobile Network Architecture','Digital Infrastructure',
 'Foundational 2G/3G mobile network architecture and protocols. Core GSM patents from 1980s–1990s expired. OpenBTS and Osmocom projects implement open-source GSM — used for rural connectivity where proprietary equipment is unaffordable.',
 'Various — Ericsson, Nokia, Motorola (original GSM patents)','Public Domain','1990s–2000s',
 'Reduce rural connectivity infrastructure cost',
 'Pan-African — especially rural sub-Saharan Africa',
 'https://osmocom.org',
 'OpenBTS and Osmocom projects implement open-source GSM on expired patents.',
 'DTO Verified','May 2026',
 ARRAY['telecoms','GSM','mobile network','rural connectivity','open source'],'High',true),

('Linux-Based Government & Enterprise Systems','Digital Infrastructure',
 'Linux operating system and associated open-source enterprise software. Completely free. Multiple African governments including Rwanda and South Africa have already implemented Linux-based government systems.',
 'Linux Foundation / various open source','Public Domain','1991 (ongoing)',
 'Eliminate Microsoft, Oracle, and SAP licensing costs across African government and enterprise',
 'Pan-African',
 'https://kernel.org',
 'Rwanda''s government uses open-source systems extensively.',
 'DTO Verified','May 2026',
 ARRAY['Linux','open source','government','enterprise software','digital sovereignty'],'Medium',true),

('NIST Cybersecurity Framework Implementation','Digital Infrastructure',
 'The US NIST Cybersecurity Framework — a comprehensive, free framework for managing cybersecurity risk. Freely available for any organisation in any country. Critical as African businesses adopt IoT-connected manufacturing.',
 'NIST (US government — freely released)','Public Domain','2014 (ongoing, free)',
 'Implement international-standard cybersecurity at zero framework licensing cost',
 'Pan-African',
 'https://nist.gov/cyberframework',
 'Uzoma Charles Njoku''s cybersecurity background makes DTO uniquely positioned to advise on African NIST implementation.',
 'DTO Verified','May 2026',
 ARRAY['cybersecurity','NIST','framework','IoT','digital security'],'Medium',true),

-- ══ WATER & SANITATION (3) ═══════════════════════════════
('Slow Sand Filtration — Community Water Treatment','Water & Sanitation',
 'Biological water purification through slow sand filtration. In the public domain for over 100 years. Over 400 million Africans lack access to safe drinking water. Operates without electricity.',
 'Various (original 1800s–1900s)','Public Domain','Pre-1920',
 'Provide safe drinking water infrastructure at minimal technology cost — without electricity',
 'Pan-African — especially rural sub-Saharan Africa',
 'https://www.who.int',
 'Complete design specifications from WHO and UNICEF — free.',
 'DTO Verified','May 2026',
 ARRAY['water','sanitation','filtration','rural','off-grid','public health'],'Low',true),

('Borehole Drilling & Hand Pump Systems','Water & Sanitation',
 'Manual and mechanised borehole drilling techniques and hand pump designs (India Mark II, Afridev, Bush Pump). All foundational designs fully public domain — several were specifically developed for African conditions.',
 'Various / UNICEF / WHO','Public Domain','Various — all pre-1990',
 'Provide rural water access without ongoing electricity costs',
 'Pan-African — especially rural sub-Saharan Africa',
 'https://www.unicef.org',
 'India Mark II and Afridev hand pump designs freely available from UNICEF.',
 'DTO Verified','May 2026',
 ARRAY['water','borehole','hand pump','rural','WASH','sanitation'],'Low',true),

('Multi-Stage Flash (MSF) Desalination','Water & Sanitation',
 'Thermal desalination converting seawater and brackish water to fresh water. Core MSF process patents from 1950s–1970s fully expired. Critical for North Africa and coastal East Africa facing freshwater scarcity.',
 'Various (original 1950s–70s)','Public Domain','Pre-1980',
 'Eliminate freshwater scarcity in water-stressed North and coastal East Africa',
 'Egypt, Libya, Algeria, Tunisia, Morocco, Kenya, Djibouti, Somalia, Eritrea, Cape Verde',
 'https://patents.google.com',
 'Solar-powered MSF desalination offers zero-fuel solution.',
 'DTO Verified','May 2026',
 ARRAY['desalination','water','coastal','North Africa','solar'],'High',true),

-- ══ MINING & MINERALS (5) ════════════════════════════════
('Froth Flotation — Mineral Concentration','Mining & Minerals',
 'Mineral processing technique separating valuable minerals from ore. Core froth flotation patents from early 1900s fully expired. DRC and Zambia account for 4.2MT/yr copper output. DRC produces 97% of African cobalt.',
 'Various (original patents 1905–1940s)','Public Domain','Pre-1950',
 'Process Africa''s mineral wealth domestically — stop exporting raw ore',
 'DRC, Zambia, Ghana, South Africa, Tanzania, Morocco, Guinea, Zimbabwe, Mozambique, Sierra Leone',
 'https://patents.google.com',
 'DRC-Zambia Battery Valley initiative creates immediate demand for domestic cobalt processing.',
 'DTO Verified','May 2026',
 ARRAY['mining','flotation','cobalt','copper','mineral processing','DRC'],'High',true),

('Hydrometallurgy — Solvent Extraction & Electrowinning (SX-EW)','Mining & Minerals',
 'Copper and cobalt extraction using solvent extraction and electrowinning — producing high-purity metal directly from ore without smelting. All foundational SX-EW process patents expired.',
 'Various (original patents 1960s–1980s)','Public Domain','Pre-1990',
 'Multiply the value captured from Africa''s copper and cobalt',
 'DRC, Zambia, Zimbabwe, Tanzania, Eritrea, Morocco, South Africa, Namibia',
 'https://patents.google.com',
 'Morocco''s Managem Group already uses hydrometallurgy for cobalt processing.',
 'DTO Verified','May 2026',
 ARRAY['mining','hydrometallurgy','cobalt','copper','electrowinning','SX-EW'],'High',true),

('Gold Cyanide Leaching & Carbon-in-Pulp (CIP) Process','Mining & Minerals',
 'Standard gold extraction process. All foundational CIP patents expired. Ghana is Africa''s largest gold producer outside South Africa. Most small and medium-scale African miners use inefficient artisanal methods.',
 'Various (original CIP patents 1970s–1980s)','Public Domain','Pre-1990',
 'Increase gold recovery from African ore bodies',
 'Ghana, South Africa, Tanzania, Mali, Burkina Faso, DRC, Côte d''Ivoire, Guinea, Zimbabwe, Sudan',
 'https://patents.google.com',
 'Environmental management of cyanide is critical. UNIDO Mining branch provides advisory.',
 'DTO Verified','May 2026',
 ARRAY['mining','gold','cyanide leaching','CIP','West Africa','Southern Africa'],'High',true),

('Phosphate Processing — Superphosphate Fertiliser Production','Mining & Minerals',
 'Chemical processing of phosphate rock into superphosphate and triple superphosphate fertilisers. Morocco holds 75% of global phosphate reserves but exports mostly raw rock and phosphoric acid.',
 'Various (original patents pre-1960)','Public Domain','Pre-1960',
 'Multiply phosphate export value by processing into finished fertilisers',
 'Morocco, Tunisia, Algeria, Egypt, Togo, Senegal, South Africa',
 'https://patents.google.com',
 'Morocco''s OCP Group is expanding into fertiliser production domestically — demonstrating commercial viability.',
 'DTO Verified','May 2026',
 ARRAY['phosphate','fertiliser','mining','Morocco','food security','chemical'],'High',true),

('Diamond Cutting & Polishing Techniques','Mining & Minerals',
 'Industrial diamond cutting, sawing, bruting, and polishing techniques. Africa produces approximately 32% of global diamond reserves. Most raw diamonds are cut and polished in Belgium, India, and Israel.',
 'Various (original cutting and polishing machinery patents pre-1960)','Public Domain','Pre-1960',
 'Cut and polish African diamonds in Africa — retain the majority of value domestically',
 'Botswana, Angola, DRC, South Africa, Namibia, Zimbabwe, Sierra Leone, Lesotho',
 'https://patents.google.com',
 'Botswana has made the most progress — Debswana now requires a significant percentage of diamonds to be cut locally.',
 'DTO Verified','May 2026',
 ARRAY['diamonds','gemstone','polishing','Botswana','Southern Africa','value chain'],'Medium',true),

-- ══ CEMENT & CONSTRUCTION (3) ════════════════════════════
('Rotary Kiln Cement Production','Cement & Construction',
 'Core technology for cement manufacturing. All fundamental rotary kiln patents expired pre-1980. Nigeria''s Dangote Cement and BUA Cement, and Ethiopia''s MIDROC Cement demonstrate commercial viability.',
 'Various (1800s–1970s)','Public Domain','Pre-1980',
 'Eliminate technology licensing on cement plants across Africa',
 'Pan-African — especially Nigeria, Ethiopia, Kenya, Ghana, Tanzania, South Africa, Egypt, Morocco, Algeria',
 'https://patents.google.com',
 'Strong AfCFTA opportunity for regional cement supply chains.',
 'DTO Verified','May 2026',
 ARRAY['cement','construction','kiln','Dangote','manufacturing'],'High',true),

('Compressed Earth Block (CEB) — Affordable Housing Technology','Cement & Construction',
 'Compressed Earth Block machines press raw earth with small amounts of cement to produce strong, affordable building blocks. Africa faces a housing deficit of approximately 50 million units.',
 'Various (original designs 1950s–1970s — CINVA Ram and variants)','Public Domain','Pre-1980',
 'Reduce housing construction cost by 30–50% using locally available earth',
 'Pan-African — especially sub-Saharan Africa',
 'https://patentscope.wipo.int',
 'CINVA Ram design and all variants fully public domain. Widely implemented in Rwanda, Kenya, Uganda, and Ghana.',
 'DTO Verified','May 2026',
 ARRAY['housing','construction','affordable housing','earth block','low-cost'],'Low',true),

('Fired Clay Brick Manufacturing','Cement & Construction',
 'Industrial fired clay brick production using tunnel kilns and Hoffman kilns. All core kiln designs and firing process patents expired. Clay is available in virtually all African countries.',
 'Various (original kiln patents pre-1900)','Public Domain','Pre-1920',
 'Industrialise Africa''s most common building material production',
 'Pan-African',
 'https://patents.google.com',
 'Kenya and South Africa have well-developed brick manufacturing industries that can serve as regional knowledge hubs.',
 'DTO Verified','May 2026',
 ARRAY['brick','clay','kiln','construction','building materials'],'Medium',true),

-- ══ CHEMICALS & PLASTICS (5) ════════════════════════════
('Chlor-Alkali Process — Chlorine & Caustic Soda Production','Chemicals & Plastics',
 'Electrolytic production of chlorine and sodium hydroxide from salt water. All core process patents expired. Essential industrial chemicals used in water treatment, paper production, soap manufacturing, and textile processing.',
 'Various (original patents 1890s–1950s)','Public Domain','Pre-1960',
 'Produce essential industrial chemicals domestically',
 'South Africa, Nigeria, Egypt, Morocco, Kenya, Tanzania, Ghana, Algeria',
 'https://patents.google.com',
 'South Africa has existing chlor-alkali production. UNIDO Chemical Industry provides advisory.',
 'DTO Verified','May 2026',
 ARRAY['chlorine','caustic soda','electrochemistry','chemicals','industrial'],'High',true),

('Soap & Detergent Manufacturing — Saponification Process','Chemicals & Plastics',
 'Industrial soap production through saponification. All foundational process patents expired for over 100 years. West Africa produces significant palm oil and groundnut oil — feedstocks for soap production.',
 'Various (original patents pre-1900)','Public Domain','Pre-1920',
 'Produce soap from Africa''s own palm oil and groundnut oil',
 'Pan-African — especially West Africa (palm oil producers), East Africa',
 'https://patents.google.com',
 'Uses palm oil + caustic soda — creating a natural value chain linkage with chlor-alkali production.',
 'DTO Verified','May 2026',
 ARRAY['soap','detergent','palm oil','saponification','FMCG','West Africa'],'Low',true),

('Polypropylene (PP) Packaging Film & Bags','Chemicals & Plastics',
 'Production of polypropylene packaging films and woven bags. Core PP processing patents from 1950s–1970s expired. Woven PP bags are ubiquitous across Africa for grain, cement, fertiliser, and agricultural product packaging.',
 'Montecatini / Natta (original PP patents — Nobel Prize 1963, patents expired)','Public Domain','Pre-1980',
 'Produce packaging domestically from African petrochemical feedstocks',
 'Nigeria, South Africa, Egypt, Morocco, Kenya, Ghana, Algeria, Tanzania',
 'https://patents.google.com',
 'Nigeria''s NNPC and South Africa''s Sasol produce petrochemical feedstocks.',
 'DTO Verified','May 2026',
 ARRAY['plastics','packaging','polypropylene','petrochemical','manufacturing'],'Medium',true),

('Sulphuric Acid Production — Contact Process','Chemicals & Plastics',
 'Industrial sulphuric acid production. All core patents expired for over 100 years. Used in fertiliser production, mineral processing, battery manufacturing. Africa''s mining sector generates sulphur dioxide that can be converted to sulphuric acid.',
 'Various (original contact process patents pre-1910)','Public Domain','Pre-1920',
 'Produce Africa''s most-needed industrial chemical domestically — from mining sector by-products',
 'South Africa, DRC, Zambia, Morocco, Tanzania, Zimbabwe, Namibia',
 'https://patents.google.com',
 'Morocco''s phosphate processing requires large volumes of sulphuric acid — domestic production would reduce costs.',
 'DTO Verified','May 2026',
 ARRAY['sulphuric acid','chemicals','mining','fertiliser','industrial'],'High',true),

('Activated Carbon Production from Agricultural Waste','Chemicals & Plastics',
 'Production of activated carbon from agricultural waste — coconut shells, palm kernel shells, rice husks, wood chips. Essential for water treatment, air purification, and gold mining.',
 'Various (original activation process patents pre-1950)','Public Domain','Pre-1960',
 'Produce activated carbon from Africa''s agricultural waste — supply water treatment and mining sectors',
 'Ghana, Nigeria, Côte d''Ivoire, Kenya, Tanzania, Mozambique, South Africa, Uganda',
 'https://patents.google.com',
 'Ghana, Tanzania, and South Africa are the largest gold mining markets requiring activated carbon.',
 'DTO Verified','May 2026',
 ARRAY['activated carbon','waste-to-value','water treatment','mining','agricultural waste'],'Medium',true),

-- ══ PAPER & PACKAGING (3) ════════════════════════════════
('Kraft Pulping Process — Paper & Cardboard Production','Paper & Packaging',
 'Chemical pulping of wood or agricultural residues to produce paper pulp. Core Kraft process patents expired for over 100 years. Africa imports most paper and packaging despite having significant forestry resources.',
 'Various (original Kraft process patents 1880s–1900s)','Public Domain','Pre-1910',
 'Produce paper and packaging domestically from Africa''s forestry and agricultural residues',
 'South Africa, Nigeria, Kenya, Ethiopia, Tanzania, Ghana, Cameroon, Congo, Algeria, Morocco',
 'https://patents.google.com',
 'South Africa''s Sappi and Mondi are major African paper producers — regional knowledge base exists.',
 'DTO Verified','May 2026',
 ARRAY['paper','pulp','packaging','forestry','Kraft','manufacturing'],'High',true),

('Corrugated Cardboard Box Manufacturing','Paper & Packaging',
 'Production of corrugated cardboard boxes. All foundational corrugating machine designs expired. The entire African e-commerce sector (growing at 15%+ CAGR) needs affordable domestic packaging.',
 'Various (original corrugating machine patents 1880s–1940s)','Public Domain','Pre-1950',
 'Produce packaging for Africa''s growing e-commerce and export sectors domestically',
 'Pan-African — especially Nigeria, South Africa, Kenya, Ghana, Ethiopia, Egypt, Morocco',
 'https://patents.google.com',
 'Strong domestic demand from agriculture, manufacturing, e-commerce, and export sectors.',
 'DTO Verified','May 2026',
 ARRAY['cardboard','packaging','e-commerce','corrugated','manufacturing'],'Medium',true),

('Glass Container Manufacturing — Blow-Mould Process','Paper & Packaging',
 'Glass bottle and container production using blow-mould processes. All foundational glass container manufacturing patents expired. Sand (the primary raw material) is abundantly available across Africa.',
 'Various (original blow-mould patents 1890s–1950s)','Public Domain','Pre-1960',
 'Produce glass containers from Africa''s abundant sand resources',
 'South Africa, Nigeria, Kenya, Ethiopia, Ghana, Tanzania, Morocco, Egypt, Algeria',
 'https://patents.google.com',
 'South Africa''s Consol Glass is Africa''s largest glass manufacturer and can serve as a regional knowledge hub.',
 'DTO Verified','May 2026',
 ARRAY['glass','containers','packaging','sand','manufacturing'],'High',true);

-- Verify
SELECT COUNT(*) as total, sector, COUNT(*) as count FROM patents GROUP BY sector ORDER BY count DESC;
