export default function Terms() {
  return (
    <div style={{ position: 'relative', zIndex: 1, paddingTop: 64 }}>
      <div style={{ maxWidth: 820, margin: '0 auto', padding: '3rem 2rem 5rem' }}>
        <div className="eyebrow">Legal</div>
        <h2 className="serif-title">Terms & Conditions</h2>
        <div style={{ fontFamily: "'DM Mono', monospace", fontSize: '.68rem', color: 'var(--gold)', letterSpacing: '.1em', marginBottom: '2.5rem' }}>Effective: 1 August 2026 · Jurisdiction: England and Wales</div>

        {[
          { h: '1. Who We Are', p: [`The Diaspora Technology Observatory ("DTO", "we", "us", "our") is an independent research platform operated by Uzoma Charles Njoku, based in the United Kingdom. Contact: hello@dtoportal.com. The website is available at dtoportal.com.`, `DTO is an independent, self-funded research project. It is not affiliated with any government, development bank, corporation, patent authority, or institution unless explicitly stated.`] },
          { h: '2. Acceptance of Terms', p: [`By accessing or using dtoportal.com ("the Platform"), you agree to these Terms and Conditions in full. If you do not agree, please do not use the Platform.`, `These Terms apply to all users — individuals, organisations, government bodies, and commercial entities — in all countries.`] },
          { h: '3. Nature of Information — Research Intelligence, Not Legal Advice', p: [`CRITICAL DISCLAIMER: The Diaspora Technology Observatory provides RESEARCH INTELLIGENCE, not legal advice. Nothing on this Platform constitutes legal advice, and no information on this Platform should be treated as legal advice.`, `Patent status is jurisdiction-specific, complex, and subject to change. A patent that has expired in one country may be active in another. The DTO library reflects our research findings as of the stated verification date — but patent status can change, databases can contain errors, and new patents can cover improvements to otherwise free technologies.`, `DO NOT manufacture any product on the basis of DTO research alone. Always: (i) independently verify patent status through qualified IP legal counsel in your specific country of manufacture; (ii) obtain all required regulatory approvals from the relevant national authority (NAFDAC, SAHPRA, KEBS, EDA, etc.); (iii) confirm that no other IP rights (trademarks, trade secrets, regulatory data exclusivity) restrict your use of the technology; (iv) check that the information is current as of your date of intended manufacture.`, `DTO accepts no liability for any decisions, actions, or losses arising from reliance on this research.`] },
          { h: '4. Free Access — Patent Library', p: [`The core patent library is provided free of charge. Browsing, searching, and viewing all entries in the library is free for all users.`, `We reserve the right to modify, update, or remove entries from the library at any time without notice, based on updated verification or changed legal status.`] },
          { h: '5. Paid Products — Sector Reports', p: [`Sector intelligence reports are available for purchase via Lemon Squeezy at prices listed on the Shop page. All prices are in GBP and include VAT where applicable.`, `Reports are delivered as PDF files. Once downloaded, reports are non-refundable — by purchasing you accept that you are buying a digital product delivered immediately. If you experience a technical problem preventing download, contact hello@dtoportal.com within 48 hours of purchase.`, `Reports are licensed for the purchaser's personal or organisational use only. You may not redistribute, resell, sub-license, or publish report content as your own work.`] },
          { h: '6. Consultations', p: [`One free consultation is available per organisation. DTO reserves the right to determine what constitutes a separate organisation.`, `Consultations are provided via email and are limited to the public domain research published on this Platform. Consultations do not constitute legal advice.`, `DTO reserves the right to decline consultation requests at its discretion.`] },
          { h: '7. Intellectual Property', p: [`The research, writing, methodology, and presentation of information on this Platform is the intellectual property of Uzoma Charles Njoku. You may not reproduce, copy, distribute, or publish material from this Platform without prior written permission.`, `The technologies described in the library are in the public domain or are covered by third-party licences. DTO makes no claim of ownership over any of the technologies described.`, `'DTO', 'Diaspora Technology Observatory', and the associated hexagonal logo are original works of Uzoma Charles Njoku.`] },
          { h: '8. Privacy & Data', p: [`When you submit a consultation request, we collect your name, organisation, country, email, sector, and message. This information is used solely to respond to your request and is stored in a secure database.`, `When you subscribe to our newsletter, we store your email address to send you updates about the Platform. You can unsubscribe at any time.`, `We use Google Analytics to understand how people use this Platform. Analytics data is aggregated and not personally identifiable. You can opt out via the cookie consent banner.`, `We do not sell, share, or otherwise transfer your personal data to third parties for marketing purposes.`, `You have the right to request access to, correction of, or deletion of any personal data we hold about you. Email hello@dtoportal.com to exercise these rights.`, `By using this Platform, you consent to data processing as described above in accordance with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018.`] },
          { h: '9. Cookies', p: [`This Platform uses cookies for two purposes: (i) Google Analytics cookies to understand visitor behaviour in aggregate; (ii) A consent preference cookie to remember your cookie choice. We do not use advertising, tracking, or third-party marketing cookies.`, `You can decline analytics cookies via the consent banner on your first visit.`] },
          { h: '10. Limitation of Liability', p: [`To the fullest extent permitted by applicable law, DTO and Uzoma Charles Njoku accept no liability for: (i) any losses, damages, or costs arising from reliance on information published on this Platform; (ii) patent infringement actions resulting from manufacturing decisions made on the basis of DTO research; (iii) regulatory action resulting from manufacture without proper national authority approval; (iv) any indirect, consequential, or special losses arising from use of this Platform.`, `Our total liability to you for any claim arising from use of this Platform shall not exceed the amount you have paid us in the 12 months preceding the claim.`] },
          { h: '11. External Links', p: [`This Platform links to external sources including WIPO, USPTO, Espacenet, the Medicines Patent Pool, and other databases. We are not responsible for the content, accuracy, or availability of external websites. Linking does not constitute endorsement.`] },
          { h: '12. Governing Law', p: [`These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.`] },
          { h: '13. Contact & Amendments', p: [`To contact us: hello@dtoportal.com. We reserve the right to amend these Terms at any time. Continued use of the Platform following amendments constitutes acceptance of the revised Terms. The effective date at the top of this page reflects the date of last amendment.`] },
        ].map(({ h, p }) => (
          <div key={h} className="terms-section">
            <h3>{h}</h3>
            {p.map((para, i) => <p key={i}>{para}</p>)}
          </div>
        ))}
      </div>
    </div>
  )
}
